import { Sparkles, CheckCircle2, XCircle } from 'lucide-react';
import Badge from '../../../components/ui/Badge';
import type { CompileRecord, CorporateRule, ExampleResult, PolicyState, Tier, VersionStatus } from '../../../api/cpg';
import {
  STATE_LABEL, STATE_VARIANT, TIER_LABEL, TIER_VARIANT, VERSION_STATUS_LABEL, VERSION_STATUS_VARIANT, describeRule, exampleResultLine,
} from '../../../lib/cpg-policy';

/** Small building blocks shared by the policy pages. */

export function TierBadge({ tier }: { tier: Tier }) {
  return <Badge variant={TIER_VARIANT[tier]} className="whitespace-nowrap">{TIER_LABEL[tier]}</Badge>;
}

export function StateBadge({ state }: { state: PolicyState }) {
  return <Badge variant={STATE_VARIANT[state]} className="whitespace-nowrap">{STATE_LABEL[state]}</Badge>;
}

export function VersionStatusBadge({ status }: { status: VersionStatus }) {
  return <Badge variant={VERSION_STATUS_VARIANT[status]} className="whitespace-nowrap">{VERSION_STATUS_LABEL[status]}</Badge>;
}

/**
 * The label every piece of LLM output carries (spec §14.1): who generated
 * it, that it may be inaccurate, and that nothing is active until someone
 * other than the author approves it.
 */
export function GeneratedNotice({ provider, model, children }: { provider: string | null; model: string | null; children?: React.ReactNode }) {
  const by = provider ? `${provider}${model ? `/${model}` : ''}` : 'the configured LLM provider';
  return (
    <div className="flex items-start gap-2 rounded-lg border border-accent/30 bg-accent-dim px-3 py-2 text-xs" data-testid="generated-notice">
      <Sparkles size={14} className="text-accent shrink-0 mt-0.5" />
      <div>
        <p className="text-text-primary font-medium">Generated by {by}, may be inaccurate.</p>
        <p className="text-text-secondary mt-0.5">
          {children ?? 'Review it before proposing. A compiled rule is never active on its own: it takes effect only after someone other than you approves it.'}
        </p>
      </div>
    </div>
  );
}

/** A compiled rule: the plain-English reading derived from its data, and the exact JSON. */
export function RuleView({ rule, testId }: { rule: CorporateRule; testId?: string }) {
  return (
    <div className="space-y-3" data-testid={testId}>
      <div>
        <p className="text-xs text-text-muted mb-1">What the rule does (read from the rule itself; this text is not generated)</p>
        <ul className="list-disc pl-5 space-y-0.5 text-sm text-text-primary">
          {describeRule(rule).map((line) => <li key={line}>{line}</li>)}
        </ul>
      </div>
      <details>
        <summary className="text-xs text-text-secondary cursor-pointer hover:text-accent">Show the exact rule (JSON the scanner evaluates)</summary>
        <pre className="mt-2 text-xs font-mono bg-surface border border-border rounded-lg p-3 overflow-x-auto whitespace-pre-wrap break-all">{JSON.stringify(rule, null, 2)}</pre>
      </details>
    </div>
  );
}

export function ExampleResults({ results }: { results: ExampleResult[] }) {
  if (results.length === 0) return null;
  return (
    <ul className="space-y-1" data-testid="example-results">
      {results.map((r) => (
        <li key={`${r.kind}-${r.index}`} className={`flex items-start gap-2 text-xs ${r.passed ? 'text-text-secondary' : 'text-danger'}`}>
          {r.passed ? <CheckCircle2 size={14} className="text-success shrink-0 mt-0.5" /> : <XCircle size={14} className="shrink-0 mt-0.5" />}
          <span>{exampleResultLine(r)}</span>
        </li>
      ))}
    </ul>
  );
}

/** Rejection reasons of a compile record, verbatim, one per line. */
export function RejectionReasons({ record }: { record: CompileRecord }) {
  const reasons = record.rejection?.reasons ?? [];
  if (reasons.length === 0) return null;
  return (
    <ul className="list-disc pl-5 space-y-0.5 text-sm text-danger" data-testid="rejection-reasons">
      {reasons.map((r, i) => <li key={`${i}-${r}`}>{r}</li>)}
    </ul>
  );
}

/** A full-length identifier (ids and hashes are never shortened). */
export function Mono({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <span className={`font-mono text-xs break-all ${className}`}>{children}</span>;
}

/** A labelled value in a page's summary grid. */
export function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs text-text-muted mb-1">{label}</p>
      <div className="text-text-primary">{children}</div>
    </div>
  );
}
