import type { Finding } from '../match/rule-matcher.js';

/**
 * Generate auto-fix suggestions for findings.
 */
export function generateSuggestions(findings: Finding[]): Finding[] {
  return findings.map((f) => ({
    ...f,
    suggestion: getSuggestionForEffect(f.rule.effect, f.sdk, f.rule.ruleKey),
  }));
}

function getSuggestionForEffect(effect: string, sdk: string, ruleKey: string): string {
  switch (effect) {
    case 'deny':
      return `This AI operation may be prohibited under ${ruleKey}. Consider:\n` +
        `1. Adding human oversight before this AI call executes\n` +
        `2. Implementing a conformity assessment process\n` +
        `3. Consulting legal counsel about this specific use case`;

    case 'require_disclosure':
      return `Add AI disclosure to responses from this ${sdk} call:\n\n` +
        `// Add header to HTTP responses:\n` +
        `res.header('X-AI-Generated', 'true');\n\n` +
        `// Or add to response body:\n` +
        `{ ...response, _ai_disclosure: 'This content was generated by an AI system.' }`;

    case 'allow_with_audit':
      return `Wrap this ${sdk} call with audit logging:\n\n` +
        `import { auditLog } from './compliance/audit';\n\n` +
        `const result = await ${getCallExample(sdk)};\n` +
        `await auditLog({\n` +
        `  action: 'ai_inference',\n` +
        `  model: '${getModelExample(sdk)}',\n` +
        `  timestamp: new Date().toISOString(),\n` +
        `});`;

    case 'flag':
      return `This AI operation is flagged for review under ${ruleKey}.\n` +
        `No action required, but consider documenting your compliance rationale.`;

    default:
      return `Review ${ruleKey} for compliance requirements.`;
  }
}

function getCallExample(sdk: string): string {
  const examples: Record<string, string> = {
    '@anthropic-ai/sdk': 'anthropic.messages.create({ ... })',
    'openai': 'openai.chat.completions.create({ ... })',
    '@google/generative-ai': 'model.generateContent({ ... })',
  };
  return examples[sdk] ?? 'aiClient.generate({ ... })';
}

function getModelExample(sdk: string): string {
  const examples: Record<string, string> = {
    '@anthropic-ai/sdk': 'claude-sonnet',
    'openai': 'gpt-4',
    '@google/generative-ai': 'gemini-pro',
  };
  return examples[sdk] ?? 'ai-model';
}
