import type { Finding } from '../match/rule-matcher.js';

/** The languages a suggestion can show code for; anything else gets prose only. */
type SuggestionLanguage = 'python' | 'javascript' | 'other';

/**
 * Generate auto-fix suggestions for findings. Code examples match the
 * finding's file language and never name a model: the audit record logs the
 * model the call actually used.
 */
export function generateSuggestions(findings: Finding[]): Finding[] {
  return findings.map((f) => ({
    ...f,
    suggestion: getSuggestionForEffect(f.rule.effect, f.sdk, f.rule.ruleKey, languageOf(f.file)),
  }));
}

function languageOf(file: string): SuggestionLanguage {
  const ext = /\.([A-Za-z0-9]+)$/.exec(file)?.[1]?.toLowerCase();
  if (ext === 'py') return 'python';
  if (ext && ['js', 'jsx', 'mjs', 'cjs', 'ts', 'tsx', 'mts', 'cts'].includes(ext)) return 'javascript';
  return 'other';
}

function getSuggestionForEffect(effect: string, sdk: string, ruleKey: string, lang: SuggestionLanguage): string {
  switch (effect) {
    case 'deny':
      return `This AI operation may be prohibited under ${ruleKey}. Consider:\n` +
        `1. Adding human oversight before this AI call executes\n` +
        `2. Implementing a conformity assessment process\n` +
        `3. Consulting legal counsel about this specific use case`;

    case 'require_disclosure':
      return `Add AI disclosure to responses from this ${sdk} call:\n\n` + disclosureExample(lang);

    case 'allow_with_audit':
      return `Wrap this ${sdk} call with audit logging:\n\n` + auditExample(sdk, lang);

    case 'flag':
      return `This AI operation is flagged for review under ${ruleKey}.\n` +
        `No action required, but consider documenting your compliance rationale.`;

    default:
      return `Review ${ruleKey} for compliance requirements.`;
  }
}

function disclosureExample(lang: SuggestionLanguage): string {
  switch (lang) {
    case 'python':
      return `# Add header to HTTP responses:\n` +
        `response.headers["X-AI-Generated"] = "true"\n\n` +
        `# Or add to response body:\n` +
        `{**body, "_ai_disclosure": "This content was generated by an AI system."}`;
    case 'javascript':
      return `// Add header to HTTP responses:\n` +
        `res.header('X-AI-Generated', 'true');\n\n` +
        `// Or add to response body:\n` +
        `{ ...response, _ai_disclosure: 'This content was generated by an AI system.' }`;
    default:
      return `- Set the HTTP response header X-AI-Generated: true, or\n` +
        `- Add an _ai_disclosure field to the response body stating that the content was generated by an AI system.`;
  }
}

function auditExample(sdk: string, lang: SuggestionLanguage): string {
  switch (lang) {
    case 'python':
      return `from datetime import datetime, timezone\n` +
        `from compliance.audit import audit_log  # your audit logger\n\n` +
        `result = ${pythonCall(sdk)}\n` +
        `audit_log(\n` +
        `    action="ai_inference",\n` +
        `    model=request["model"],\n` +
        `    timestamp=datetime.now(timezone.utc).isoformat(),\n` +
        `)`;
    case 'javascript':
      return `import { auditLog } from './compliance/audit'; // your audit logger\n\n` +
        `const result = await ${javascriptCall(sdk)};\n` +
        `await auditLog({\n` +
        `  action: 'ai_inference',\n` +
        `  model: request.model,\n` +
        `  timestamp: new Date().toISOString(),\n` +
        `});`;
    default:
      return `After the call returns, write an audit record with the action (ai_inference), ` +
        `the model the request used and a UTC ISO-8601 timestamp.`;
  }
}

function javascriptCall(sdk: string): string {
  const examples: Record<string, string> = {
    '@anthropic-ai/sdk': 'anthropic.messages.create(request)',
    'openai': 'openai.chat.completions.create(request)',
    '@google/generative-ai': 'genAI.getGenerativeModel({ model: request.model }).generateContent(request.contents)',
  };
  return examples[sdk] ?? 'aiClient.generate(request)';
}

function pythonCall(sdk: string): string {
  const examples: Record<string, string> = {
    'anthropic': 'anthropic_client.messages.create(**request)',
    'openai': 'openai_client.chat.completions.create(**request)',
    'google.generativeai': 'genai.GenerativeModel(request["model"]).generate_content(request["contents"])',
  };
  return examples[sdk] ?? 'ai_client.generate(**request)';
}
