/**
 * Ingestion adapter framework tests (mocked HTTP — no live network).
 * ==================================================================
 *
 * Covers, against realistic government-API fixtures:
 *   - Channel-hierarchy routing: API sources → the right adapter; non-API
 *     sources → no adapter (fall through to the scraper).
 *   - eCFR adapter: parses the official XML → byte_exact + correct point-in-time
 *     coordinate; conditional-fetch SKIP when unchanged; HARD-FAIL (no fallback)
 *     when the official fetch fails.
 *   - Federal Register adapter: resolves to full_text_xml_url, hashes the
 *     artifact, correct coordinate; conditional skip; hard-fail.
 *   - EUR-Lex adapter: still works via the registry (CELEX folded in) and
 *     produces byte_exact + the resolved-CELEX coordinate.
 *   - scrapeSource integration: an API URL routes to the adapter (official_api,
 *     byte_exact, coordinate); a failed adapter fetch HARD-FAILS rather than
 *     scraping; a non-API URL is NOT claimed by any adapter.
 */

import { describe, it, expect, vi } from 'vitest';

vi.mock('../../../logger.js', () => ({
  logger: { info: () => {}, warn: () => {}, error: () => {}, debug: () => {} },
}));

import { selectAdapter, listAdapters, hasAdapter } from './registry.js';
import { ecfrAdapter, parseEcfrTarget } from './ecfr.js';
import { federalRegisterAdapter, extractFrDocumentNumber } from './federal-register.js';
import { eurLexAdapter } from './eur-lex.js';
import { nistOscalAdapter, oscalCatalogToText } from './nist-oscal.js';
import { legislationUkAdapter, parseUkTarget } from './legislation-uk.js';
import { officialXmlToText, clmlToText } from './shared.js';
import type { AdapterResult, AdapterNotModified } from './types.js';
import { sha256Hex } from './shared.js';
import { REGULATORY_SOURCES } from '../registry.js';
import { createHash } from 'node:crypto';

// ─── Fixtures ────────────────────────────────────────────────────────────────

const LEGAL_PARA =
  'The provider of a high-risk artificial intelligence system shall establish, ' +
  'implement, document and maintain a risk management system in relation to the ' +
  'high-risk system throughout its entire lifecycle, and shall retain the technical ' +
  'documentation and the logs automatically generated by the system for a period ' +
  'appropriate to the intended purpose of the system and applicable legal obligations.';

const ECFR_XML = `<?xml version="1.0"?>
<DIV5 N="164" TYPE="PART" VOLUME="2">
<HEAD>PART 164—SECURITY AND PRIVACY</HEAD>
<AUTH><HED>Authority:</HED><PSPACE>42 U.S.C. 1302(a); 42 U.S.C. 1320d-1320d-9.</PSPACE></AUTH>
<DIV6 N="E" TYPE="SUBPART">
<HEAD>Subpart E—Privacy of Individually Identifiable Health Information</HEAD>
<DIV8 N="164.502" TYPE="SECTION">
<HEAD>§ 164.502 Uses and disclosures of protected health information: General rules.</HEAD>
<P>${LEGAL_PARA}</P>
<P>A covered entity or business associate may not use or disclose protected health information except as permitted or required by this subpart or by subpart C of part 160 of this subchapter.</P>
</DIV8>
<DIV8 N="164.504" TYPE="SECTION">
<HEAD>§ 164.504 Uses and disclosures: Organizational requirements.</HEAD>
<P>A covered entity may disclose protected health information to a business associate and may allow a business associate to create receive maintain or transmit protected health information on its behalf only if the covered entity obtains satisfactory assurances that the business associate will appropriately safeguard the information as required by this subpart.</P>
</DIV8>
</DIV6>
</DIV5>`;

const ECFR_TITLES = {
  titles: [
    { number: 45, name: 'Public Welfare', latest_amended_on: '2024-05-10', latest_issue_date: '2024-05-17', up_to_date_as_of: '2026-07-23', reserved: false },
    { number: 21, name: 'Food and Drugs', latest_amended_on: '2024-04-01', latest_issue_date: '2024-04-02', up_to_date_as_of: '2026-07-23', reserved: false },
  ],
};

const ECFR_VERSIONS_45_164 = {
  content_versions: [
    { date: '2016-12-30', amendment_date: '2013-01-25', issue_date: '2016-12-30', identifier: '164.502', part: '164', subpart: 'E', substantive: true, removed: false },
    { date: '2016-12-30', amendment_date: '2024-05-10', issue_date: '2016-12-30', identifier: '164.504', part: '164', subpart: 'E', substantive: true, removed: false },
  ],
};

const FR_DOC_2023_24283 = {
  document_number: '2023-24283',
  publication_date: '2023-11-01',
  full_text_xml_url: 'https://www.federalregister.gov/documents/full_text/xml/2023/11/01/2023-24283.xml',
  raw_text_url: 'https://www.federalregister.gov/documents/full_text/text/2023/11/01/2023-24283.txt',
  body_html_url: 'https://www.federalregister.gov/documents/full_text/html/2023/11/01/2023-24283.html',
  html_url: 'https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence',
  title: 'Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence',
  type: 'Presidential Document',
  citation: '88 FR 75191',
};

const FR_XML = `<?xml version="1.0"?>
<PRESDOCU>
<HD SOURCE="HED">Executive Order 14110 of October 30, 2023</HD>
<HD SOURCE="HD1">Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence</HD>
<FP>By the authority vested in me as President by the Constitution and the laws of the United States of America, it is hereby ordered as follows.</FP>
<P>${LEGAL_PARA}</P>
<P>Agencies shall, consistent with applicable law, develop and use artificial intelligence in a manner that advances equity, protects civil rights, and safeguards the privacy of the American people, and shall report on their progress to the Director of the Office of Management and Budget.</P>
</PRESDOCU>`;

const EURLEX_XHTML = `<html><body>
<h1>Regulation (EU) 2024/1689 — Artificial Intelligence Act</h1>
<p>${LEGAL_PARA}</p>
<p>This Regulation lays down harmonised rules on artificial intelligence and applies to providers placing on the market or putting into service AI systems in the Union, irrespective of whether those providers are established within the Union or in a third country, and to deployers of AI systems established within the Union.</p>
</body></html>`;

// Official NIST OSCAL JSON catalog (SP 800-53 shape: catalog → groups →
// controls → parts, with nested statement items and a guidance part).
const OSCAL_SP53_URL =
  'https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json';
const OSCAL_CSF_URL =
  'https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/CSF/v2.0/json/NIST_CSF_v2.0_catalog.json';

const OSCAL_SP53 = {
  catalog: {
    uuid: 'aaaa-bbbb-cccc-dddd',
    metadata: {
      title: 'Electronic (OSCAL) Version of NIST SP 800-53 Rev 5 Controls',
      version: '5.2.0',
      'oscal-version': '1.2.2',
      'last-modified': '2026-05-11T16:01:09.00000-00:00',
    },
    groups: [
      {
        id: 'ac',
        class: 'family',
        title: 'Access Control',
        controls: [
          {
            id: 'ac-1',
            class: 'SP800-53',
            title: 'Policy and Procedures',
            parts: [
              {
                id: 'ac-1_smt',
                name: 'statement',
                prose:
                  'Develop, document, and disseminate to organizational personnel an access control policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance.',
                parts: [
                  {
                    id: 'ac-1_smt.a',
                    name: 'item',
                    prose:
                      'Review and update the current access control policy and the access control procedures at an organization-defined frequency and following organization-defined events.',
                  },
                ],
              },
              {
                id: 'ac-1_gdn',
                name: 'guidance',
                prose:
                  'Access control policy and procedures address the controls in the AC family that are implemented within systems and organizations.',
              },
            ],
          },
        ],
      },
    ],
  },
};
const OSCAL_SP53_JSON = JSON.stringify(OSCAL_SP53);

// Official legislation.gov.uk CLML XML. Metadata (title/valid/modified) and the
// Commentaries block must be stripped; only the enacted Body prose survives.
const UK_CLML = `<?xml version="1.0" encoding="UTF-8"?>
<Legislation xmlns="http://www.legislation.gov.uk/namespaces/legislation" DocumentURI="http://www.legislation.gov.uk/ukpga/2018/12" IdURI="http://www.legislation.gov.uk/id/ukpga/2018/12">
<ukm:Metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:ukm="http://www.legislation.gov.uk/namespaces/metadata">
<dc:title>Data Protection Act 2018</dc:title>
<dc:modified>2026-07-09</dc:modified>
<dct:valid>2026-06-19</dct:valid>
</ukm:Metadata>
<Primary><Body>
<Part id="part-1"><Number><Strong>PART 1</Strong></Number><Title>Preliminary</Title>
<P1group><Title>Overview</Title>
<P1 id="section-1"><Pnumber>1</Pnumber><P1para>
<P2 id="section-1-1"><Pnumber>1</Pnumber><P2para><Text>This Act makes provision about the processing of personal data and the protection of individuals with regard to that processing throughout the United Kingdom.</Text></P2para></P2>
<P2 id="section-1-2"><Pnumber>2</Pnumber><P2para><Text>Most processing of personal data is subject to the UK GDPR, which lays down general obligations for controllers and processors and confers rights on data subjects.</Text></P2para></P2>
<P2 id="section-1-3"><Pnumber>3</Pnumber><P2para><Text>Part 2 supplements the UK GDPR and applies a broadly equivalent regime to certain types of processing to which the UK GDPR does not apply.</Text></P2para></P2>
</P1para></P1>
</P1group></Part>
</Body></Primary>
<Commentaries><Commentary id="c1" Type="F"><Para><Text>THIS-COMMENTARY-MUST-NOT-APPEAR words substituted by regulations.</Text></Para></Commentary></Commentaries>
</Legislation>`;

// ─── Mock fetch helpers ──────────────────────────────────────────────────────

function jsonResp(body: unknown) {
  return {
    ok: true,
    status: 200,
    url: '',
    headers: { get: () => null },
    json: async () => body,
  };
}

/** A 304 Not Modified response (no body). */
function resp304() {
  return { ok: false, status: 304, url: '', headers: { get: () => null } };
}

/** Read the If-None-Match header a mock fetch received (init.headers is plain). */
function ifNoneMatch(init: any): string | undefined {
  return init?.headers?.['If-None-Match'];
}

function bytesResp(url: string, text: string, contentType = 'application/xml', status = 200) {
  const buf = Buffer.from(text, 'utf-8');
  return {
    ok: status >= 200 && status < 300,
    status,
    url,
    headers: {
      get: (h: string) => {
        const k = h.toLowerCase();
        if (k === 'content-type') return contentType;
        return null;
      },
    },
    arrayBuffer: async () => buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
    body: { cancel: async () => {} },
  };
}

// ─── officialXmlToText ───────────────────────────────────────────────────────

describe('officialXmlToText', () => {
  it('extracts section headings and paragraphs in document order without duplication', () => {
    const text = officialXmlToText(ECFR_XML);
    expect(text).toContain('§ 164.502 Uses and disclosures');
    expect(text).toContain('§ 164.504 Uses and disclosures: Organizational requirements');
    expect(text).toContain('risk management system');
    // Authority text (inside <AUTH>) appears exactly once (via PSPACE, not
    // double-counted through the AUTH container).
    const occurrences = text.split('42 U.S.C. 1302(a)').length - 1;
    expect(occurrences).toBe(1);
  });
});

// ─── Routing / channel hierarchy ─────────────────────────────────────────────

describe('channel-hierarchy router', () => {
  it('routes an eCFR API URL to the eCFR adapter', () => {
    const a = selectAdapter('https://www.ecfr.gov/api/versioner/v1/full/current/title-45.xml?part=164&subpart=E');
    expect(a?.id).toBe('ecfr');
    expect(a?.channel).toBe('official_api');
  });

  it('routes a Federal Register document URL to the FR adapter', () => {
    const a = selectAdapter('https://www.federalregister.gov/api/v1/documents/2023-24283.json');
    expect(a?.id).toBe('federal_register');
  });

  it('routes a govinfo Federal Register package URL to the FR adapter', () => {
    const a = selectAdapter('https://www.govinfo.gov/content/pkg/FR-2023-11-01/html/2023-24283.htm');
    expect(a?.id).toBe('federal_register');
  });

  it('routes a EUR-Lex CELEX URL to the EUR-Lex adapter', () => {
    const a = selectAdapter('https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689');
    expect(a?.id).toBe('eur_lex_cellar');
  });

  it('routes a NIST OSCAL raw JSON URL to the NIST OSCAL adapter', () => {
    const a = selectAdapter(OSCAL_SP53_URL);
    expect(a?.id).toBe('nist_oscal');
    expect(a?.channel).toBe('official_api');
    expect(selectAdapter(OSCAL_CSF_URL)?.id).toBe('nist_oscal');
  });

  it('does NOT claim the GSA FedRAMP OSCAL repo (different repo, not usnistgov/oscal-content)', () => {
    expect(
      selectAdapter('https://github.com/GSA/fedramp-automation/tree/master/dist/content/rev5/baselines/json'),
    ).toBeNull();
  });

  it('routes a legislation.gov.uk URL to the legislation.gov.uk adapter', () => {
    const a = selectAdapter('https://www.legislation.gov.uk/ukpga/2018/12');
    expect(a?.id).toBe('legislation_gov_uk');
    expect(selectAdapter('https://www.legislation.gov.uk/ukpga/2018/12/section/1/data.xml')?.id).toBe('legislation_gov_uk');
  });

  it('does NOT claim a gov.uk policy paper (not legislation.gov.uk)', () => {
    expect(
      selectAdapter('https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach/white-paper'),
    ).toBeNull();
  });

  it('returns null for a non-API source (falls through to the scraper)', () => {
    expect(selectAdapter('https://gdpr-info.eu/')).toBeNull();
    expect(selectAdapter('https://www.law.cornell.edu/cfr/text/45/part-164/subpart-E')).toBeNull();
    expect(hasAdapter('https://gdpr-info.eu/')).toBe(false);
  });

  it('lists adapters in descending channel priority (official_api first)', () => {
    const ids = listAdapters().map((a) => a.channel);
    expect(ids.every((c) => c === 'official_api')).toBe(true);
  });
});

describe('URL parsers', () => {
  it('parseEcfrTarget extracts title/part/subpart/date', () => {
    const t = parseEcfrTarget('https://www.ecfr.gov/api/versioner/v1/full/current/title-45.xml?part=164&subpart=E');
    expect(t).toEqual({ date: 'current', title: 45, part: '164', subpart: 'E', section: null });
  });

  it('extractFrDocumentNumber handles API, permalink and govinfo forms', () => {
    expect(extractFrDocumentNumber('https://www.federalregister.gov/api/v1/documents/2023-24283.json')).toBe('2023-24283');
    expect(extractFrDocumentNumber('https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe')).toBe('2023-24283');
    expect(extractFrDocumentNumber('https://www.govinfo.gov/content/pkg/FR-2023-11-01/html/2023-24283.htm')).toBe('2023-24283');
    expect(extractFrDocumentNumber('https://gdpr-info.eu/')).toBeNull();
  });
});

// ─── eCFR adapter ────────────────────────────────────────────────────────────

describe('eCFR adapter', () => {
  const URL = 'https://www.ecfr.gov/api/versioner/v1/full/current/title-45.xml?part=164&subpart=E';

  function ecfrFetch(opts: { xmlStatus?: number; fullXmlCalls?: { n: number } } = {}) {
    return vi.fn(async (input: any) => {
      const url = String(input);
      if (url.includes('/titles.json')) return jsonResp(ECFR_TITLES);
      if (url.includes('/versions/title-45.json')) return jsonResp(ECFR_VERSIONS_45_164);
      if (url.includes('/full/') && url.includes('title-45.xml')) {
        if (opts.fullXmlCalls) opts.fullXmlCalls.n++;
        return bytesResp(url, ECFR_XML, 'application/xml', opts.xmlStatus ?? 200);
      }
      throw new Error(`Unexpected fetch: ${url}`);
    }) as unknown as typeof fetch;
  }

  it('fetches the official XML → byte_exact with the correct point-in-time coordinate', async () => {
    const fetchImpl = ecfrFetch();
    const outcome = (await ecfrAdapter.fetch(URL, { fetchImpl })) as AdapterResult;

    expect(outcome.kind).toBe('fetched');
    expect(outcome.provenanceMode).toBe('byte_exact');
    expect(outcome.channel).toBe('official_api');
    // Byte-exact receipt: rawBytesHash == sha256 of the served XML bytes.
    expect(outcome.rawBytesHash).toBe(createHash('sha256').update(Buffer.from(ECFR_XML, 'utf-8')).digest('hex'));
    expect(outcome.contentHash).toBe(sha256Hex(outcome.content));
    expect(outcome.content).toContain('§ 164.502');

    // Coordinate: concrete resolved date (from up_to_date_as_of), title/part/subpart.
    const c = outcome.pointInTimeCoordinate;
    expect(c.authority).toBe('ecfr');
    expect(c.fields.title).toBe(45);
    expect(c.fields.part).toBe('164');
    expect(c.fields.subpart).toBe('E');
    expect(c.fields.date).toBe('2026-07-23'); // resolved from up_to_date_as_of, NOT "current"
    expect(c.fields.partLatestAmendedOn).toBe('2024-05-10'); // max amendment across the part
    expect(c.citation).toContain('45 CFR Part 164 Subpart E @ 2026-07-23');
    // The fetched artifact URL carries the resolved date, not "current".
    expect(outcome.sourceUrl).toContain('/full/2026-07-23/title-45.xml');
  });

  it('CONDITIONAL SKIP: unchanged part last-amended date → not_modified, no full-XML download', async () => {
    const fullXmlCalls = { n: 0 };
    const fetchImpl = ecfrFetch({ fullXmlCalls });
    const outcome = (await ecfrAdapter.fetch(URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: {
        authority: 'ecfr',
        citation: 'prior',
        fields: { partLatestAmendedOn: '2024-05-10' },
      },
    })) as AdapterNotModified;

    expect(outcome.kind).toBe('not_modified');
    expect(fullXmlCalls.n).toBe(0); // heavy artifact was NOT re-downloaded
  });

  it('re-fetches when the part was amended since the last coordinate', async () => {
    const fullXmlCalls = { n: 0 };
    const fetchImpl = ecfrFetch({ fullXmlCalls });
    const outcome = await ecfrAdapter.fetch(URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: { authority: 'ecfr', citation: 'prior', fields: { partLatestAmendedOn: '2020-01-01' } },
    });
    expect(outcome.kind).toBe('fetched');
    expect(fullXmlCalls.n).toBe(1);
  });

  it('HARD-FAILS (throws, no fallback) when the official XML fetch fails', async () => {
    const fetchImpl = ecfrFetch({ xmlStatus: 503 });
    await expect(ecfrAdapter.fetch(URL, { fetchImpl })).rejects.toThrow(/HTTP 503|Official fetch failed/i);
  });
});

// ─── Federal Register adapter ────────────────────────────────────────────────

describe('Federal Register adapter', () => {
  const URL = 'https://www.federalregister.gov/api/v1/documents/2023-24283.json';

  function frFetch(opts: { xmlStatus?: number; artifactCalls?: { n: number } } = {}) {
    return vi.fn(async (input: any) => {
      const url = String(input);
      if (url.includes('/api/v1/documents/2023-24283.json')) return jsonResp(FR_DOC_2023_24283);
      if (url.includes('/full_text/xml/')) {
        if (opts.artifactCalls) opts.artifactCalls.n++;
        return bytesResp(url, FR_XML, 'application/xml', opts.xmlStatus ?? 200);
      }
      throw new Error(`Unexpected fetch: ${url}`);
    }) as unknown as typeof fetch;
  }

  it('resolves to full_text_xml_url, hashes the artifact → byte_exact + FR coordinate', async () => {
    const fetchImpl = frFetch();
    const outcome = (await federalRegisterAdapter.fetch(URL, { fetchImpl })) as AdapterResult;

    expect(outcome.provenanceMode).toBe('byte_exact');
    expect(outcome.rawBytesHash).toBe(createHash('sha256').update(Buffer.from(FR_XML, 'utf-8')).digest('hex'));
    expect(outcome.sourceUrl).toBe(FR_DOC_2023_24283.full_text_xml_url);
    expect(outcome.content).toContain('Executive Order 14110');

    const c = outcome.pointInTimeCoordinate;
    expect(c.authority).toBe('federal_register');
    expect(c.fields.documentNumber).toBe('2023-24283');
    expect(c.fields.publicationDate).toBe('2023-11-01');
    expect(c.fields.artifactKind).toBe('xml');
    expect(c.citation).toContain('88 FR 75191');
  });

  it('CONDITIONAL SKIP: same immutable FR document already ingested → not_modified', async () => {
    const artifactCalls = { n: 0 };
    const fetchImpl = frFetch({ artifactCalls });
    const outcome = (await federalRegisterAdapter.fetch(URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: { authority: 'federal_register', citation: 'prior', fields: { documentNumber: '2023-24283' } },
    })) as AdapterNotModified;

    expect(outcome.kind).toBe('not_modified');
    expect(artifactCalls.n).toBe(0);
  });

  it('HARD-FAILS when the artifact fetch fails', async () => {
    const fetchImpl = frFetch({ xmlStatus: 500 });
    await expect(federalRegisterAdapter.fetch(URL, { fetchImpl })).rejects.toThrow(/HTTP 500|Official fetch failed/i);
  });
});

// ─── EUR-Lex adapter (CELEX folded into the registry) ────────────────────────

describe('EUR-Lex adapter (folded CELEX resolver)', () => {
  const URL = 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689';

  // Routes SPARQL (versions/amends) + the Cellar resource fetch.
  function eurlexFetch(opts: { versions?: string[]; cellarStatus?: number; cellarCalls?: { n: number } } = {}) {
    const versions = opts.versions ?? []; // [] → resolves to as-adopted 32024R1689
    return vi.fn(async (input: any) => {
      const url = String(input);
      if (url.includes('/webapi/rdf/sparql')) {
        const q = decodeURIComponent(url);
        if (q.includes('STRSTARTS')) return jsonResp({ results: { bindings: versions.map((celex) => ({ celex: { value: celex } })) } });
        if (q.includes('amends')) return jsonResp({ results: { bindings: [] } });
        throw new Error('unexpected sparql');
      }
      if (url.includes('/resource/celex/')) {
        if (opts.cellarCalls) opts.cellarCalls.n++;
        return bytesResp(url, EURLEX_XHTML, 'application/xhtml+xml', opts.cellarStatus ?? 200);
      }
      throw new Error(`Unexpected fetch: ${url}`);
    }) as unknown as typeof fetch;
  }

  it('works via the registry and produces byte_exact + resolved-CELEX coordinate', async () => {
    const a = selectAdapter(URL)!;
    expect(a.id).toBe('eur_lex_cellar');

    const fetchImpl = eurlexFetch();
    const outcome = (await a.fetch(URL, { fetchImpl })) as AdapterResult;

    expect(outcome.provenanceMode).toBe('byte_exact');
    expect(outcome.rawBytesHash).toBe(createHash('sha256').update(Buffer.from(EURLEX_XHTML, 'utf-8')).digest('hex'));
    expect(outcome.content).toContain('Artificial Intelligence Act');

    const c = outcome.pointInTimeCoordinate;
    expect(c.authority).toBe('eur_lex_cellar');
    expect(c.fields.resolvedCelex).toBe('32024R1689'); // as-adopted (no consolidation in fixture)
    expect(c.fields.versionIri).toBe('https://publications.europa.eu/resource/celex/32024R1689');
    expect(outcome.sourceUrl).toContain('/resource/celex/32024R1689');
  });

  it('CONDITIONAL SKIP: same resolved CELEX + no pending amendments → not_modified', async () => {
    const cellarCalls = { n: 0 };
    const fetchImpl = eurlexFetch({ cellarCalls });
    const outcome = (await eurLexAdapter.fetch(URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: { authority: 'eur_lex_cellar', citation: 'prior', fields: { resolvedCelex: '32024R1689' } },
    })) as AdapterNotModified;

    expect(outcome.kind).toBe('not_modified');
    expect(cellarCalls.n).toBe(0);
  });

  it('HARD-FAILS when the Cellar artifact fetch fails', async () => {
    const fetchImpl = eurlexFetch({ cellarStatus: 500 });
    await expect(eurLexAdapter.fetch(URL, { fetchImpl })).rejects.toThrow(/HTTP 500|Official fetch failed/i);
  });
});

// ─── OSCAL / CLML parsers ────────────────────────────────────────────────────

describe('oscalCatalogToText', () => {
  it('parses an OSCAL catalog into non-empty, document-ordered control text', () => {
    const text = oscalCatalogToText(OSCAL_SP53);
    expect(text.length).toBeGreaterThan(200);
    expect(text).toContain('Access Control'); // group title
    expect(text).toContain('AC-1'); // control id (upper-cased)
    expect(text).toContain('Policy and Procedures'); // control title
    expect(text).toContain('Develop, document, and disseminate'); // statement prose
    expect(text).toContain('Review and update the current access control policy'); // nested item prose
    expect(text).toContain('address the controls in the AC family'); // guidance prose
  });

  it('returns empty string when there is no catalog root', () => {
    expect(oscalCatalogToText({} as never)).toBe('');
  });
});

describe('clmlToText', () => {
  it('extracts the enacted body prose and drops metadata + commentaries', () => {
    const text = clmlToText(UK_CLML);
    expect(text.length).toBeGreaterThan(200);
    expect(text).toContain('This Act makes provision about the processing of personal data');
    expect(text).toContain('Preliminary'); // Part title heading
    expect(text).toContain('Overview'); // P1group title heading
    // Metadata title lives in <dc:title> which is stripped from the body text.
    // Commentary footnotes must NOT leak into the enacted text.
    expect(text).not.toContain('THIS-COMMENTARY-MUST-NOT-APPEAR');
  });
});

// ─── NIST OSCAL adapter ──────────────────────────────────────────────────────

describe('NIST OSCAL adapter', () => {
  function oscalFetch(opts: { status?: number; calls?: { n: number }; etag?: string } = {}) {
    return vi.fn(async (input: any, init: any) => {
      const url = String(input);
      if (opts.etag && ifNoneMatch(init) === opts.etag) return resp304();
      if (/\.json$/i.test(url)) {
        if (opts.calls) opts.calls.n++;
        return bytesResp(url, OSCAL_SP53_JSON, 'application/json', opts.status ?? 200);
      }
      throw new Error(`Unexpected fetch: ${url}`);
    }) as unknown as typeof fetch;
  }

  it('fetches the official OSCAL JSON → byte_exact with the correct coordinate', async () => {
    const fetchImpl = oscalFetch();
    const outcome = (await nistOscalAdapter.fetch(OSCAL_SP53_URL, { fetchImpl })) as AdapterResult;

    expect(outcome.kind).toBe('fetched');
    expect(outcome.provenanceMode).toBe('byte_exact');
    expect(outcome.channel).toBe('official_api');
    // Byte-exact receipt: hash is over the served JSON bytes, not the text.
    expect(outcome.rawBytesHash).toBe(
      createHash('sha256').update(Buffer.from(OSCAL_SP53_JSON, 'utf-8')).digest('hex'),
    );
    expect(outcome.contentHash).toBe(sha256Hex(outcome.content));
    // OSCAL parsing produced readable control text.
    expect(outcome.content).toContain('Policy and Procedures');
    expect(outcome.content.length).toBeGreaterThan(200);

    const c = outcome.pointInTimeCoordinate;
    expect(c.authority).toBe('nist_oscal');
    expect(c.fields.catalog).toBe('NIST SP 800-53 Rev 5');
    expect(c.fields.catalogVersion).toBe('5.2.0');
    expect(c.fields.oscalVersion).toBe('1.2.2');
    expect(c.fields.lastModified).toBe('2026-05-11T16:01:09.00000-00:00');
    expect(c.fields.artifactUrl).toBe(OSCAL_SP53_URL);
    expect(c.citation).toContain('NIST SP 800-53 Rev 5 v5.2.0');
  });

  it('derives the CSF catalog name from the repo path', async () => {
    const fetchImpl = oscalFetch();
    const outcome = (await nistOscalAdapter.fetch(OSCAL_CSF_URL, { fetchImpl })) as AdapterResult;
    // Fixture body is the SP53 JSON, but the name derivation is path-based.
    expect(outcome.pointInTimeCoordinate.fields.catalog).toBe('NIST Cybersecurity Framework 2.0');
  });

  it('CONDITIONAL SKIP: HTTP 304 → not_modified, no artifact download', async () => {
    const calls = { n: 0 };
    const fetchImpl = oscalFetch({ calls, etag: 'etag-oscal' });
    const outcome = (await nistOscalAdapter.fetch(OSCAL_SP53_URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: {
        authority: 'nist_oscal',
        citation: 'prior',
        fields: { httpEtag: 'etag-oscal', catalog: 'NIST SP 800-53 Rev 5' },
      },
    })) as AdapterNotModified;

    expect(outcome.kind).toBe('not_modified');
    expect(calls.n).toBe(0); // heavy artifact was NOT re-downloaded
  });

  it('HARD-FAILS (throws, no PDF fallback) when the OSCAL fetch fails', async () => {
    const fetchImpl = oscalFetch({ status: 503 });
    await expect(nistOscalAdapter.fetch(OSCAL_SP53_URL, { fetchImpl })).rejects.toThrow(
      /HTTP 503|Official fetch failed/i,
    );
  });

  it('HARD-FAILS when the artifact is not valid OSCAL JSON', async () => {
    const fetchImpl = vi.fn(async (input: any) =>
      bytesResp(String(input), 'not json at all — a PDF byte stream', 'application/json'),
    ) as unknown as typeof fetch;
    await expect(nistOscalAdapter.fetch(OSCAL_SP53_URL, { fetchImpl })).rejects.toThrow(/not valid JSON/i);
  });
});

// ─── legislation.gov.uk adapter ──────────────────────────────────────────────

describe('legislation.gov.uk adapter', () => {
  const URL = 'https://www.legislation.gov.uk/ukpga/2018/12';

  function ukFetch(opts: { status?: number; calls?: { n: number }; etag?: string } = {}) {
    return vi.fn(async (input: any, init: any) => {
      const url = String(input);
      if (opts.etag && ifNoneMatch(init) === opts.etag) return resp304();
      if (url.includes('/data.xml')) {
        if (opts.calls) opts.calls.n++;
        return bytesResp(url, UK_CLML, 'application/xml', opts.status ?? 200);
      }
      throw new Error(`Unexpected fetch: ${url}`);
    }) as unknown as typeof fetch;
  }

  it('parseUkTarget builds the /data.xml URL and detects a point-in-time segment', () => {
    expect(parseUkTarget(URL)).toEqual({
      uri: 'https://www.legislation.gov.uk/ukpga/2018/12',
      dataXmlUrl: 'https://www.legislation.gov.uk/ukpga/2018/12/data.xml',
      versionInUrl: null,
    });
    expect(parseUkTarget('https://www.legislation.gov.uk/ukpga/2018/12/2020-01-01')).toEqual({
      uri: 'https://www.legislation.gov.uk/ukpga/2018/12/2020-01-01',
      dataXmlUrl: 'https://www.legislation.gov.uk/ukpga/2018/12/2020-01-01/data.xml',
      versionInUrl: '2020-01-01',
    });
    // Already a /data.xml URL is normalized, not doubled.
    expect(parseUkTarget('https://www.legislation.gov.uk/ukpga/2018/12/data.xml')?.dataXmlUrl).toBe(
      'https://www.legislation.gov.uk/ukpga/2018/12/data.xml',
    );
    expect(parseUkTarget('https://www.gov.uk/government/publications/white-paper')).toBeNull();
  });

  it('fetches the official CLML XML → byte_exact + {uri, pointInTime, artifactUrl} coordinate', async () => {
    const fetchImpl = ukFetch();
    const outcome = (await legislationUkAdapter.fetch(URL, { fetchImpl })) as AdapterResult;

    expect(outcome.provenanceMode).toBe('byte_exact');
    expect(outcome.channel).toBe('official_api');
    expect(outcome.rawBytesHash).toBe(
      createHash('sha256').update(Buffer.from(UK_CLML, 'utf-8')).digest('hex'),
    );
    expect(outcome.sourceUrl).toContain('/ukpga/2018/12/data.xml');
    // CLML parsed into readable enacted text.
    expect(outcome.content).toContain('This Act makes provision about the processing of personal data');
    expect(outcome.content).not.toContain('THIS-COMMENTARY-MUST-NOT-APPEAR');

    const c = outcome.pointInTimeCoordinate;
    expect(c.authority).toBe('legislation_gov_uk');
    expect(c.fields.uri).toBe('http://www.legislation.gov.uk/ukpga/2018/12');
    expect(c.fields.pointInTime).toBe('2026-06-19'); // from CLML dct:valid
    expect(c.fields.title).toBe('Data Protection Act 2018');
    expect(c.fields.artifactUrl).toBe('https://www.legislation.gov.uk/ukpga/2018/12/data.xml');
    expect(c.citation).toContain('Data Protection Act 2018 @ 2026-06-19');
  });

  it('an explicit URL date segment wins as the point-in-time coordinate', async () => {
    const fetchImpl = ukFetch();
    const outcome = (await legislationUkAdapter.fetch(
      'https://www.legislation.gov.uk/ukpga/2018/12/2020-01-01',
      { fetchImpl },
    )) as AdapterResult;
    expect(outcome.pointInTimeCoordinate.fields.pointInTime).toBe('2020-01-01');
    expect(outcome.pointInTimeCoordinate.fields.versionInUrl).toBe('2020-01-01');
    expect(outcome.sourceUrl).toContain('/ukpga/2018/12/2020-01-01/data.xml');
  });

  it('CONDITIONAL SKIP: HTTP 304 → not_modified, no artifact download', async () => {
    const calls = { n: 0 };
    const fetchImpl = ukFetch({ calls, etag: 'etag-uk' });
    const outcome = (await legislationUkAdapter.fetch(URL, {
      fetchImpl,
      lastContentHash: 'prior-hash',
      lastCoordinate: {
        authority: 'legislation_gov_uk',
        citation: 'prior',
        fields: { httpEtag: 'etag-uk', uri: 'http://www.legislation.gov.uk/ukpga/2018/12' },
      },
    })) as AdapterNotModified;

    expect(outcome.kind).toBe('not_modified');
    expect(calls.n).toBe(0);
  });

  it('HARD-FAILS (throws, no scrape fallback) when the CLML fetch fails', async () => {
    const fetchImpl = ukFetch({ status: 500 });
    await expect(legislationUkAdapter.fetch(URL, { fetchImpl })).rejects.toThrow(
      /HTTP 500|Official fetch failed/i,
    );
  });
});

// ─── Migrated registry sources resolve to the right adapter ──────────────────

describe('registry source migration → adapter routing', () => {
  function sourceByName(name: string) {
    const s = REGULATORY_SOURCES.find((x) => x.name === name);
    if (!s) throw new Error(`registry source not found: ${name}`);
    return s;
  }

  it('NIST SP 800-53 Rev 5 now routes to the NIST OSCAL adapter', () => {
    const s = sourceByName('NIST SP 800-53 Rev 5 (Security Controls)');
    expect(s.channel).toBe('official_api');
    expect(selectAdapter(s.url)?.id).toBe('nist_oscal');
    expect(s.fallbackUrl).toContain('NIST.SP.800-53r5.pdf');
  });

  it('NIST Cybersecurity Framework 2.0 now routes to the NIST OSCAL adapter', () => {
    const s = sourceByName('NIST Cybersecurity Framework 2.0');
    expect(s.channel).toBe('official_api');
    expect(selectAdapter(s.url)?.id).toBe('nist_oscal');
    expect(s.fallbackUrl).toContain('NIST.CSWP.29.pdf');
  });

  it('NIST AI RMF stays on its PDF channel (no OSCAL exists) — no adapter claims it', () => {
    const s = sourceByName('NIST AI Risk Management Framework');
    expect(s.channel).toBeUndefined();
    expect(s.parserType).toBe('pdf');
    expect(selectAdapter(s.url)).toBeNull();
  });

  it('UK AI White Paper stays on the gov.uk scrape channel — no adapter claims it', () => {
    const s = sourceByName('UK AI Regulation White Paper');
    expect(s.channel).toBeUndefined();
    expect(selectAdapter(s.url)).toBeNull();
  });
});
