import { useCallback, useEffect, useMemo, useState } from 'react';
import { SlidersHorizontal, Info } from 'lucide-react';
import Card from '../../components/ui/Card';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import Modal from '../../components/ui/Modal';
import Spinner from '../../components/ui/Spinner';
import ErrorState from '../../components/ui/ErrorState';
import DataFreshness from '../../components/ui/DataFreshness';
import { getCpgSettings, listOrgUsers, updateCpgSettings, type CpgSettings, type OrgUser } from '../../api/cpg';
import { useCpgMe } from '../../hooks/useCpgMe';
import { useCpgStore } from '../../stores/cpgStore';
import { useAuthStore } from '../../stores/authStore';
import { cpgErrorMessage } from '../../lib/cpg-errors';
import { formatActor, hasOrgPermission } from '../../lib/cpg-permissions';
import { formatDateTime } from '../../lib/formatters';
import GovernanceHeader from './GovernanceHeader';

/**
 * /governance/settings (E15, E16): turn governance on or off and choose
 * whether reviewer context is generated by the instance's LLM provider,
 * with the disclosure the owner's decision D1 requires.
 */
export default function GovernanceSettings() {
  const { me } = useCpgMe();
  const orgName = useAuthStore((s) => s.org?.name ?? null);
  const setCpgEnabled = useCpgStore((s) => s.setCpgEnabled);
  const canManage = hasOrgPermission(me, 'org.settings.manage');
  const canReadUsers = hasOrgPermission(me, 'org.members.read');

  const [settings, setSettings] = useState<CpgSettings | null>(null);
  const [fetchedAt, setFetchedAt] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [users, setUsers] = useState<OrgUser[] | null>(null);
  const [usersError, setUsersError] = useState<string | null>(null);
  const [retryKey, setRetryKey] = useState(0);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'ok' | 'err'; text: string } | null>(null);
  const [confirmEnabled, setConfirmEnabled] = useState<boolean | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const s = await getCpgSettings();
        if (cancelled) return;
        setSettings(s);
        setFetchedAt(new Date().toISOString());
        setLoadError(null);
      } catch (err) {
        if (!cancelled) setLoadError(cpgErrorMessage(err, 'Failed to load governance settings'));
      }
      if (!canReadUsers) return;
      try {
        const u = await listOrgUsers();
        if (!cancelled) { setUsers(u); setUsersError(null); }
      } catch (err) {
        if (!cancelled) setUsersError(cpgErrorMessage(err, 'Could not load user names'));
      }
    })();
    return () => { cancelled = true; };
  }, [retryKey, canReadUsers]);

  const retry = useCallback(() => { setLoadError(null); setSettings(null); setRetryKey((k) => k + 1); }, []);

  async function save(patch: { enabled?: boolean; reviewerContextLlm?: boolean }, done: string) {
    setSaving(true);
    setMessage(null);
    try {
      const s = await updateCpgSettings(patch);
      setSettings(s);
      setFetchedAt(new Date().toISOString());
      setCpgEnabled(s.enabled);
      setMessage({ type: 'ok', text: done });
    } catch (err) {
      setMessage({ type: 'err', text: cpgErrorMessage(err, 'Failed to save the setting') });
    }
    setSaving(false);
  }

  const usersById = useMemo(() => new Map((users ?? []).map((u) => [u.id, u])), [users]);

  return (
    <div>
      <GovernanceHeader icon={SlidersHorizontal} title="Governance settings" subtitle={`Settings for ${orgName ?? 'your organization'}`} />
      {loadError ? (
        <ErrorState message={loadError} onRetry={retry} />
      ) : !settings ? (
        <div className="flex justify-center py-16"><Spinner /></div>
      ) : (
        <>
          <SettingsView
            settings={settings}
            canManage={canManage}
            saving={saving}
            actorName={formatActor(settings.updatedBy, usersById)}
            onToggleEnabled={() => setConfirmEnabled(!settings.enabled)}
            onToggleReviewerContext={() => void save(
              { reviewerContextLlm: !settings.reviewerContextLlm },
              settings.reviewerContextLlm ? 'Reviewer context generation turned off.' : 'Reviewer context generation turned on.',
            )}
          />
          {message && (
            <p className={`text-xs mt-3 ${message.type === 'ok' ? 'text-success' : 'text-danger'}`} role={message.type === 'err' ? 'alert' : 'status'}>
              {message.text}
            </p>
          )}
          {usersError && <ErrorState compact message={`${usersError}; actors are shown by id.`} />}
          <DataFreshness fetchedAt={fetchedAt} className="mt-4" />
        </>
      )}

      <Modal
        open={confirmEnabled !== null}
        onClose={() => setConfirmEnabled(null)}
        title={confirmEnabled ? 'Turn on corporate policy governance?' : 'Turn off corporate policy governance?'}
        width="max-w-md"
      >
        <p className="text-sm text-text-secondary mb-4">
          {confirmEnabled
            ? 'Corporate policies, review cases and approvals become active for this organization. The change is recorded in the audit log.'
            : 'Governance stops for this organization: it behaves as it did before governance was turned on. Roles, teams and the audit log are kept. The change is recorded in the audit log.'}
        </p>
        <div className="flex justify-end gap-2">
          <Button variant="ghost" onClick={() => setConfirmEnabled(null)}>Cancel</Button>
          <Button
            variant={confirmEnabled ? 'primary' : 'danger'}
            disabled={saving}
            onClick={() => {
              const enabled = confirmEnabled === true;
              setConfirmEnabled(null);
              void save({ enabled }, enabled ? 'Governance turned on.' : 'Governance turned off.');
            }}
          >
            {confirmEnabled ? 'Turn on' : 'Turn off'}
          </Button>
        </div>
      </Modal>
    </div>
  );
}

function Switch({ checked, disabled, onChange, label }: { checked: boolean; disabled: boolean; onChange: () => void; label: string }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      aria-label={label}
      disabled={disabled}
      onClick={onChange}
      className={`relative inline-flex h-6 w-11 shrink-0 items-center rounded-full border transition disabled:opacity-50 disabled:cursor-not-allowed ${
        checked ? 'bg-accent border-accent' : 'bg-surface-raised border-border'
      }`}
    >
      <span className={`inline-block h-4 w-4 rounded-full bg-white shadow transition ${checked ? 'translate-x-6' : 'translate-x-1'}`} />
    </button>
  );
}

export function SettingsView({ settings, canManage, saving, actorName, onToggleEnabled, onToggleReviewerContext }: {
  settings: CpgSettings;
  canManage: boolean;
  saving: boolean;
  actorName: string;
  onToggleEnabled: () => void;
  onToggleReviewerContext: () => void;
}) {
  return (
    <div className="space-y-6">
      {!canManage && (
        <p className="text-sm text-text-muted flex items-center gap-2" data-testid="settings-read-only">
          <Info size={14} /> Read only. Only an Org Admin (permission <span className="font-mono text-xs">org.settings.manage</span>) can change these settings.
        </p>
      )}

      <Card>
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-sm font-semibold text-text-secondary mb-1 flex items-center gap-2">
              Corporate policy governance
              <Badge variant={settings.enabled ? 'success' : 'default'}>{settings.enabled ? 'On' : 'Off'}</Badge>
            </h2>
            <p className="text-sm text-text-muted max-w-2xl">
              Turns corporate policies, review cases and approvals on for this organization. While it is off, the
              organization works exactly as before; you can still set up roles, teams and other governance settings first.
            </p>
          </div>
          {canManage && (
            <Button variant={settings.enabled ? 'secondary' : 'primary'} size="sm" disabled={saving} onClick={onToggleEnabled}>
              {settings.enabled ? 'Turn off' : 'Turn on'}
            </Button>
          )}
        </div>
      </Card>

      <Card>
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-sm font-semibold text-text-secondary mb-1 flex items-center gap-2">
              Reviewer context
              <Badge variant={settings.reviewerContextLlm ? 'accent' : 'default'}>{settings.reviewerContextLlm ? 'On' : 'Off'}</Badge>
            </h2>
            <p className="text-sm text-text-muted max-w-2xl">
              Generates a plain-English explanation of each flagged snippet (what the code does and why it was flagged) to help
              reviewers decide.
            </p>
          </div>
          <Switch
            checked={settings.reviewerContextLlm}
            disabled={!canManage || saving}
            onChange={onToggleReviewerContext}
            label="Generate reviewer context"
          />
        </div>

        <div className="mt-4 p-3 rounded-lg border border-warning/30 bg-warning/10 text-sm" data-testid="reviewer-context-disclosure">
          <p className="text-text-primary font-medium mb-1">What leaves this Nomus instance</p>
          <p className="text-text-secondary">
            When reviewer context is on, snippets of flagged code are sent to the LLM provider configured for this Nomus
            instance. Generated context is always labelled as generated and may be inaccurate. Code is never put in
            emails or tracker tickets, whether this setting is on or off.
          </p>
          <p className="text-text-secondary mt-2" data-testid="llm-provider-status">
            {settings.llmProviderConfigured
              ? 'An LLM provider is configured on this instance, so snippets are sent to it while this setting is on.'
              : 'No LLM provider is configured on this instance, so nothing is sent and no context is generated until one is.'}
          </p>
        </div>
      </Card>

      <Card>
        <h2 className="text-sm font-semibold text-text-secondary mb-3">History</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
          <div>
            <p className="text-text-muted text-xs">Last changed</p>
            <p className="text-text-secondary" title={settings.updatedAt}>{formatDateTime(settings.updatedAt)} by {actorName}</p>
          </div>
          <div>
            <p className="text-text-muted text-xs">Roles set up for existing members</p>
            <p className="text-text-secondary" title={settings.rbacMigratedAt ?? undefined}>
              {settings.rbacMigratedAt ? formatDateTime(settings.rbacMigratedAt) : 'Not yet'}
            </p>
          </div>
        </div>
        <p className="text-xs text-text-muted mt-3">Every change is recorded in the governance audit log.</p>
      </Card>
    </div>
  );
}
