import { describe, it, expect } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { MemoryRouter } from 'react-router-dom';
import { PolicyTable } from './GovernancePolicies';
import { PolicyDetailView, DiffCard } from './PolicyDetail';
import CompileResult from './policies/CompileResult';
import * as fx from '../../test/cpg-fixtures';
import type { CompileRecord, CpgMe, PolicyDetail } from '../../api/cpg';

function html(node: React.ReactElement): string {
  return renderToStaticMarkup(<MemoryRouter>{node}</MemoryRouter>);
}
function text(node: React.ReactElement): string {
  return html(node).replace(/<[^>]+>/g, ' ').replace(/&#x27;|&#39;/g, "'").replace(/&quot;/g, '"').replace(/&amp;/g, '&').replace(/&gt;/g, '>').replace(/\s+/g, ' ');
}
function expectClean(t: string) {
  for (const re of fx.BROKEN) expect(t).not.toMatch(re);
}

const noop = () => {};
const NOW = Date.parse('2026-10-09T08:00:00.000Z');
const detail = fx.policyDetail as PolicyDetail;
const names = new Map([
  [fx.AUTHOR_ID, { name: 'Author Three', email: 'author@example.org' }],
  [fx.APPROVER_ID, { name: 'Approver Four', email: 'approver@example.org' }],
  [fx.OWNER_ID, { name: 'Owner One', email: 'owner@example.org' }],
]);
const meAs = (userId: string, permissions: string[]): CpgMe => fx.me({
  user: { id: userId, name: 'X', email: 'x@example.org' },
  permissions: permissions.map((key) => ({ key, scope: 'org' as const, scopeId: null })),
});
const view = (me: CpgMe, over: Partial<Parameters<typeof PolicyDetailView>[0]> = {}) => (
  <PolicyDetailView detail={detail} me={me} names={names} namesError={null} lapseDays={30} justProposed={false} notice={null}
    onNotice={noop} onChanged={noop} fetchedAt="2026-10-09T08:00:00.000Z" now={NOW} {...over} />
);

describe('Policy log', () => {
  it('lists state, tier, owning boards, versions and the grace period', () => {
    const t = text(<PolicyTable items={[fx.policyHead, { ...fx.policyHead, policyId: fx.V1_ID, policyKey: 'corp.no-direct-openai', title: 'No direct OpenAI calls', tier: 'prohibited', inGracePeriod: false, pendingVersionId: null, pendingVersion: null }]} now={NOW} filtered={false} canAuthor />);
    expect(t).toContain('corp.no-gpt-4-32k');
    expect(t).toContain('Review required');
    expect(t).toContain('AI Review Board');
    expect(t).toContain('v1 active');
    expect(t).toContain('v2 awaiting approval');
    expect(t).toContain('Grace period');
    expect(t).toContain('Advisory until Oct 22, 2026, 08:00 UTC (13 days), then enforced.');
    expect(t).toContain('Enforced since Oct 22, 2026, 08:00 UTC');
    expectClean(t);
  });

  it('a pending retirement is labelled as a retirement in the version column', () => {
    const t = text(<PolicyTable items={[{ ...fx.policyHead, activeVersion: 2, pendingVersion: 3, pendingVersionKind: 'retire', inGracePeriod: false }]} now={NOW} filtered={false} canAuthor />);
    expect(t).toContain('v2 active');
    expect(t).toContain('v3 retirement awaiting approval');
  });

  it('empty states for authors, readers and filters', () => {
    expect(text(<PolicyTable items={[]} now={NOW} filtered={false} canAuthor />)).toContain('needs another person');
    expect(text(<PolicyTable items={[]} now={NOW} filtered={false} canAuthor={false} />)).toContain('Policy Authors write policies');
    expect(text(<PolicyTable items={[]} now={NOW} filtered canAuthor />)).toContain('No policies in this state');
  });
});

describe('Compile result', () => {
  it('a compiled rule is labelled as generated and as not active until someone else approves it', () => {
    const t = text(<CompileResult record={fx.compiledRecord as CompileRecord} />);
    expect(t).toContain('Generated by openai/gpt-4o-mini, may be inaccurate.');
    expect(t).toContain('takes effect only after someone other than you approves it');
    expect(t).toContain('Rationale (generated)');
    expect(t).toContain('this text is not generated');
    expect(t).toContain('Flags a line matching the pattern /gpt-4-32k/ (comments ignored).');
    expect(t).toContain('Violating example 1 (src/models.ts): passed');
    expect(t).toContain(fx.COMPILE_V2_ID);
    expectClean(t);
  });

  it('shows an unexpressible reason verbatim, and failing examples', () => {
    const u = text(<CompileResult record={fx.unexpressibleRecord as CompileRecord} />);
    expect(u).toContain('Cannot be expressed as a deterministic rule');
    expect(u).toContain('Requires a judgement about design quality, which a deterministic rule cannot make.');
    expect(u).not.toContain('Generated by');
    const e = text(<CompileResult record={fx.examplesRecord as CompileRecord} />);
    expect(e).toContain('The rule does not match your examples');
    expect(e).toContain('violating example 1 (src/util.ts) produced no finding');
    expect(e).toContain('Violating example 1 (src/util.ts): FAILED, expected at least one finding, got no finding.');
    expectClean(u + e);
  });

  it('warns when the inputs changed after compiling', () => {
    expect(text(<CompileResult record={fx.compiledRecord as CompileRecord} stale />)).toContain('Compile again before proposing');
  });
});

describe('Policy detail', () => {
  it('the author sees the four-eyes refusal instead of vote buttons', () => {
    const page = html(view(meAs(fx.AUTHOR_ID, ['policy.read', 'policy.author', 'policy.approve', 'org.members.read'])));
    const t = text(view(meAs(fx.AUTHOR_ID, ['policy.read', 'policy.author', 'policy.approve', 'org.members.read'])));
    expect(t).toContain('Version 2 awaits approval');
    expect(t).toContain('0 of 1 approval so far');
    expect(t).toContain('You proposed this version, so you cannot approve or reject it.');
    expect(t).toContain('Withdraw my proposal');
    expect(page).not.toMatch(/>Approve</);
    expect(t).toContain('Proposed by author@example.org');
    expect(t).toContain('Compiled by author@example.org');
    expect(t).toContain('Lapses Nov 8, 2026, 08:00 UTC if not decided');
    expectClean(t);
  });

  it('an approver gets Approve and Reject; versions, signatures, diff and history are shown', () => {
    const t = text(view(meAs(fx.APPROVER_ID, ['policy.read', 'policy.approve'])));
    expect(t).toContain('Approve');
    expect(t).toContain('Reject');
    expect(t).not.toContain('Withdraw my proposal');
    expect(t).toContain('Signed');
    expect(t).toContain('Not signed (only approved versions are)');
    expect(t).toContain('Enforced from Oct 22, 2026, 08:00 UTC');
    expect(t).toContain('Activated and signed');
    expect(t).toContain('System (quorum reached)');
    expect(t).toContain('Grace period once approved 0 days after approval');
    expect(t).toContain('Compare versions');
    expect(t).toContain('Approved by Approver Four');
    expect(t).toContain('Approved by Approver Four · Oct 8, 2026, 08:00 UTC · quorum v1');
    expectClean(t);
  });

  it('a reader without policy.approve is told what is missing; the just-proposed notice says it is not active', () => {
    const t = text(view(meAs(fx.DEV_ID, ['policy.read']), { justProposed: true }));
    expect(t).toContain('Voting needs the policy.approve permission');
    expect(t).toContain('Version 2 is not active : it waits for approval by someone other than you.');
    expect(t).not.toContain('New version');
  });

  it('supersede history: a superseded version names its successor', () => {
    const superseded: PolicyDetail = {
      ...detail,
      policy: { ...detail.policy, activeVersion: 2, pendingVersionId: null, pendingVersion: null },
      versions: [{ ...detail.versions[0], status: 'superseded' }, { ...detail.versions[1], status: 'active', signature: 'c2ln', activatedAt: '2026-10-09T09:00:00.000Z', enforceFrom: '2026-10-09T09:00:00.000Z' }],
      events: [...detail.events, { id: '0c1d2e3f-4051-4263-9b74-8c9d0e1f2099', versionId: fx.V1_ID, version: 1, event: 'superseded', actor: 'system:quorum', details: { supersededBy: fx.V2_ID }, createdAt: '2026-10-09T09:00:00.000Z' }],
    };
    const t = text(view(meAs(fx.APPROVER_ID, ['policy.read', 'policy.approve']), { detail: superseded }));
    expect(t).toContain('Superseded by v2');
    expect(t).toContain('v1 Superseded · System (quorum reached) · by v2');
    expect(t).not.toContain('awaits approval');
  });

  it('the version diff shows what changed', () => {
    const t = text(<DiffCard versions={detail.versions} />);
    expect(t).toContain('Tier Review required Prohibited');
    expect(t).toContain('Owning boards AI Review Board AI Review Board, Legal Board');
    expect(text(<DiffCard versions={[detail.versions[0]]} />)).toContain('only one version');
  });
});
