/** Jurisdiction codes — expandable as sources are added */
export const JURISDICTIONS = {
  // Supranational
  'EU': 'European Union',
  'INTL': 'International',
  // National
  'US-FED': 'United States (Federal)',
  'UK': 'United Kingdom',
  'CN': 'China',
  'CA': 'Canada',
  'AU': 'Australia',
  'JP': 'Japan',
  'KR': 'South Korea',
  'BR': 'Brazil',
  'IN': 'India',
  'SG': 'Singapore',
  // US State-level
  'US-CA': 'California',
  'US-CO': 'Colorado',
  'US-IL': 'Illinois',
  'US-NY': 'New York',
  'US-TX': 'Texas',
  // Standards bodies
  'ISO': 'ISO/IEC Standards',
  'NIST': 'NIST Framework',
} as const;

export type JurisdictionCode = keyof typeof JURISDICTIONS;

/** Policy category labels for display */
export const CATEGORY_LABELS: Record<string, string> = {
  data_governance: 'Data Governance',
  transparency: 'Transparency',
  risk_assessment: 'Risk Assessment',
  human_oversight: 'Human Oversight',
  accountability: 'Accountability',
  fairness: 'Fairness & Non-Discrimination',
  privacy: 'Privacy',
  safety: 'Safety',
  security: 'Security',
  intellectual_property: 'Intellectual Property',
};

/** API key prefix format */
export const API_KEY_PREFIX_LIVE = 'nk_live_';
export const API_KEY_PREFIX_TEST = 'nk_test_';

/**
 * Legal disclaimer — included in every API response that returns
 * policy rules, compliance evaluations, or attestation receipts.
 * Nomus is NOT a law firm and does NOT provide legal advice.
 */
export const LEGAL_DISCLAIMER = 'Nomus is an automated regulatory monitoring tool, not a law firm or legal advisor. The information provided is generated by AI from publicly available regulatory texts and is for informational purposes only. It does not constitute legal advice, legal opinion, or legal representation. The accuracy, completeness, and applicability of any output is not guaranteed. You should consult a qualified legal professional before making compliance decisions. Use of Nomus does not create an attorney-client relationship.' as const;
