/**
 * scrapeSource × ACCESS-ESCALATION (headless + manual-upload terminal tier).
 *
 * The headless module is fully MOCKED — no browser is ever launched, so this
 * runs with NO Chromium installed. HTTP is mocked via global.fetch.
 *
 * Escalation order under test:
 *   needsHeadless        → straight to headless (plain scrape skipped)
 *   scrape block (403)   → headless escalation
 *   headless success     → 'rendered' provenance (promotable)
 *   headless blocked/unavailable → ManualUploadRequiredError (hold for manual upload)
 * A challenge/blocked page is NEVER returned as content (refuse-to-guess).
 */
import { describe, it, expect, vi, afterEach } from 'vitest';

vi.mock('../logger.js', () => ({
  logger: { info: () => {}, warn: () => {}, error: () => {}, debug: () => {} },
}));

// Mock the lazy headless module — the scraper's only coupling to Playwright.
const headless = vi.hoisted(() => ({ result: null as unknown }));
vi.mock('./headless-fetch.js', () => ({
  fetchHeadless: vi.fn(async () => headless.result),
}));

import { scrapeSource, ManualUploadRequiredError } from './scraper.js';

const LEGAL_PARA =
  'The provider of a covered artificial intelligence system that is made available to a California ' +
  'resident shall include a clear and conspicuous disclosure identifying content as generated by the ' +
  'system, retain documentation of the training data provenance for the life of the system plus ten ' +
  'years, and make available a free public detection tool that meets the accuracy standards adopted ' +
  'by the department, and shall not condition access to the system on a waiver of these rights.';

const BILL_HTML =
  `<!DOCTYPE html><html><head><title>AB-2013</title></head><body><div id="bill_all">` +
  `<h1>Assembly Bill No. 2013</h1><p>${LEGAL_PARA}</p><p>${LEGAL_PARA}</p></div></body></html>`;

function renderedSuccess() {
  return {
    kind: 'success' as const,
    renderedHtml: BILL_HTML,
    rawBytesHash: 'rendered-hash-abc',
    rawBytesSize: Buffer.byteLength(BILL_HTML, 'utf-8'),
    finalUrl: 'https://example.gov/bill?rendered',
    contentType: 'text/html; rendered-dom',
    provenanceMode: 'rendered' as const,
  };
}

const forbidden = (url: string) => ({
  ok: false, status: 403, statusText: 'Forbidden', url, redirected: false,
  headers: { get: () => '' },
});

const originalFetch = global.fetch;
afterEach(() => {
  global.fetch = originalFetch;
  headless.result = null;
  vi.clearAllMocks();
});

const URL = 'https://example.gov/bill';

describe('needsHeadless routes straight to headless (plain scrape skipped)', () => {
  it('returns a rendered capture and never issues an HTTP fetch', async () => {
    headless.result = renderedSuccess();
    global.fetch = vi.fn(async () => { throw new Error('plain fetch should not run'); }) as never;

    const r = await scrapeSource(URL, 'html', {}, { sourceId: 's1', sourceName: 'CA AB 2013', needsHeadless: true });

    expect(r.source).toBe('headless');
    expect(r.provenanceMode).toBe('rendered');
    expect(r.contentQuality).toBe('valid');
    expect(r.rawContent).toBe(BILL_HTML);       // rendered DOM preserved as provenance
    expect(r.rawBytesHash).toBe('rendered-hash-abc');
    expect(r.content).toContain('Assembly Bill No. 2013');
    expect(global.fetch).not.toHaveBeenCalled(); // plain HTTP scrape was skipped
  });

  it('holds for MANUAL UPLOAD when headless is unavailable (disabled / no browser)', async () => {
    headless.result = { kind: 'unavailable', reason: 'Headless fetch disabled' };
    global.fetch = vi.fn(async () => { throw new Error('no fetch'); }) as never;

    await expect(
      scrapeSource(URL, 'html', {}, { sourceId: 's1', sourceName: 'CA AB 2013', needsHeadless: true }),
    ).rejects.toMatchObject({ name: 'ManualUploadRequiredError', code: 'needs_manual_upload' });
  });
});

describe('scrape block (403) escalates to headless before holding', () => {
  it('scrape 403 → headless success → rendered capture', async () => {
    headless.result = renderedSuccess();
    global.fetch = vi.fn(async (input: unknown) => forbidden(String(input))) as never;

    const r = await scrapeSource(URL, 'html', {}, { sourceId: 's2', sourceName: 'Blocked Source' });

    expect((global.fetch as ReturnType<typeof vi.fn>).mock.calls.length).toBeGreaterThan(0); // plain scrape WAS attempted
    expect(r.source).toBe('headless');
    expect(r.provenanceMode).toBe('rendered');
  });

  it('scrape 403 → headless blocked (challenge) → ManualUploadRequiredError, challenge NEVER returned', async () => {
    headless.result = { kind: 'blocked', reason: 'Anti-bot challenge page detected' };
    global.fetch = vi.fn(async (input: unknown) => forbidden(String(input))) as never;

    const err = await scrapeSource(URL, 'html', {}, { sourceId: 's2', sourceName: 'Blocked Source' })
      .then(() => null)
      .catch((e) => e);

    expect(err).toBeInstanceOf(ManualUploadRequiredError);
    expect(err.code).toBe('needs_manual_upload');
    expect(err.message).toMatch(/needs_manual_upload/);
  });
});

describe('non-block outage does NOT trigger headless', () => {
  it('a timeout outage holds for manual upload without a headless attempt', async () => {
    const { fetchHeadless } = await import('./headless-fetch.js');
    headless.result = renderedSuccess(); // would succeed IF called
    // A plain outage (not a bot block): the fetch times out on every UA.
    global.fetch = vi.fn(async () => {
      throw Object.assign(new Error('The operation timed out'), { name: 'TimeoutError' });
    }) as never;

    await expect(
      scrapeSource(URL, 'html', {}, { sourceId: 's3', sourceName: 'Missing Source' }),
    ).rejects.toBeInstanceOf(ManualUploadRequiredError);

    // A timeout is a plain outage, not a bot block — headless must NOT be attempted.
    expect(fetchHeadless).not.toHaveBeenCalled();
  });
});
