/**
 * scrapeSource × ingestion-adapter integration (mocked HTTP).
 *
 *   - An official-API URL routes through the adapter: the result is
 *     official_api + byte_exact and carries a point-in-time coordinate, instead
 *     of HTML scraping.
 *   - A failed official fetch HARD-FAILS (scrapeSource throws) — it NEVER falls
 *     back to scraping stale HTML and presenting it as current law.
 *   - A conditional-fetch "not modified" short-circuits to a no-change result
 *     WITHOUT re-downloading the artifact.
 *   - A non-API URL is not claimed by any adapter (the scraper path still runs).
 */
import { describe, it, expect, vi, afterEach } from 'vitest';

vi.mock('../logger.js', () => ({
  logger: { info: () => {}, warn: () => {}, error: () => {}, debug: () => {} },
}));

import { scrapeSource } from './scraper.js';
import { selectAdapter } from './sources/adapters/registry.js';

const ECFR_URL = 'https://www.ecfr.gov/api/versioner/v1/full/current/title-45.xml?part=164&subpart=E';

const LEGAL_PARA =
  'The provider of a high-risk artificial intelligence system shall establish, implement, ' +
  'document and maintain a risk management system in relation to the high-risk system throughout ' +
  'its entire lifecycle, and shall retain the technical documentation and the logs automatically ' +
  'generated by the system for a period appropriate to the intended purpose and applicable legal obligations.';

const ECFR_XML = `<?xml version="1.0"?>
<DIV5 N="164" TYPE="PART">
<HEAD>PART 164—SECURITY AND PRIVACY</HEAD>
<DIV8 N="164.502" TYPE="SECTION">
<HEAD>§ 164.502 Uses and disclosures of protected health information.</HEAD>
<P>${LEGAL_PARA}</P>
<P>A covered entity or business associate may not use or disclose protected health information except as permitted or required by this subpart, and shall maintain reasonable and appropriate administrative, technical, and physical safeguards to protect the privacy of protected health information.</P>
</DIV8>
</DIV5>`;

const TITLES = { titles: [{ number: 45, name: 'Public Welfare', latest_amended_on: '2024-05-10', latest_issue_date: '2024-05-17', up_to_date_as_of: '2026-07-23', reserved: false }] };
const VERSIONS = { content_versions: [{ date: '2016-12-30', amendment_date: '2024-05-10', issue_date: '2016-12-30', identifier: '164.502', part: '164', subpart: 'E', substantive: true, removed: false }] };

function jsonResp(body: unknown) {
  return { ok: true, status: 200, url: '', headers: { get: () => null }, json: async () => body };
}
function bytesResp(url: string, text: string, status = 200) {
  const buf = Buffer.from(text, 'utf-8');
  return {
    ok: status >= 200 && status < 300,
    status,
    url,
    headers: { get: (h: string) => (h.toLowerCase() === 'content-type' ? 'application/xml' : null) },
    arrayBuffer: async () => buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  };
}

const originalFetch = global.fetch;
afterEach(() => {
  global.fetch = originalFetch;
  vi.restoreAllMocks();
});

function ecfrGlobalFetch(opts: { xmlStatus?: number; fullCalls?: { n: number } } = {}) {
  global.fetch = vi.fn(async (input: any) => {
    const url = String(input);
    if (url.includes('/titles.json')) return jsonResp(TITLES) as any;
    if (url.includes('/versions/title-45.json')) return jsonResp(VERSIONS) as any;
    if (url.includes('/full/') && url.includes('title-45.xml')) {
      if (opts.fullCalls) opts.fullCalls.n++;
      return bytesResp(url, ECFR_XML, opts.xmlStatus ?? 200) as any;
    }
    throw new Error(`Unexpected fetch: ${url}`);
  }) as any;
}

describe('scrapeSource routes official-API sources through the adapter', () => {
  it('eCFR URL → official_api + byte_exact + point-in-time coordinate', async () => {
    ecfrGlobalFetch();
    const result = await scrapeSource(ECFR_URL, 'html', {}, { sourceId: 's1', sourceName: 'HIPAA Privacy' });

    expect(result.source).toBe('live');
    expect(result.channel).toBe('official_api');
    expect(result.provenanceMode).toBe('byte_exact');
    expect(result.contentQuality).toBe('valid');
    expect(result.pointInTimeCoordinate?.authority).toBe('ecfr');
    expect(result.pointInTimeCoordinate?.fields.date).toBe('2026-07-23');
    expect(result.content).toContain('§ 164.502');
    // rawContent is the served XML (byte-exact receipt lives on rawBytesHash).
    expect(result.rawContent).toContain('<DIV5');
  });

  it('HARD-FAILS (throws) on a failed official fetch — never scrapes as fallback', async () => {
    ecfrGlobalFetch({ xmlStatus: 503 });
    await expect(
      scrapeSource(ECFR_URL, 'html', {}, { sourceId: 's1', sourceName: 'HIPAA Privacy' }),
    ).rejects.toThrow(/HTTP 503|Official fetch failed/i);
  });

  it('conditional not-modified short-circuits without re-downloading the artifact', async () => {
    const fullCalls = { n: 0 };
    ecfrGlobalFetch({ fullCalls });
    const result = await scrapeSource(ECFR_URL, 'html', {}, {
      sourceId: 's1',
      sourceName: 'HIPAA Privacy',
      lastContentHash: 'prior-hash',
      lastCoordinate: { authority: 'ecfr', citation: 'prior', fields: { partLatestAmendedOn: '2024-05-10' } },
    });

    expect(result.notModified).toBe(true);
    expect(result.contentHash).toBe('prior-hash'); // change-detection will report no_change
    expect(result.channel).toBe('official_api');
    expect(fullCalls.n).toBe(0);
  });

  it('a non-API URL is not claimed by any adapter', () => {
    expect(selectAdapter('https://gdpr-info.eu/')).toBeNull();
  });
});
